pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.saps.dev/static/mirror/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.saps.dev/static/mirror/' }
        mavenCentral()
    }
}

rootProject.name = 'Jyro-Client'
